---
abstract: 'RFC 2392 mid: URI implementation'
author:
  - 'Dorian Taylor, C<< <dorian at cpan.org> >>'
  - 'Dorian Taylor <dorian@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-mid
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.0
resources:
  license: http://apache.org/licenses/LICENSE-2.0
version: 0.01
